# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/dell/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-13660-DESKTOP-HP8AC3V/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/work/vivado/tw_on_fly/tw_on_fly.cache/wt [current_project]
set_property parent.project_path E:/work/vivado/tw_on_fly/tw_on_fly.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.1 [current_project]
set_property ip_output_repo e:/work/vivado/tw_on_fly/tw_on_fly.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  E:/work/crypto/twiddle_lut/files/sin_table_64x8.mem
  E:/work/crypto/twiddle_lut/files/cos_table_64x8.mem
}
read_verilog -library xil_defaultlib -sv {
  E:/work/vivado/tw_on_fly/tw_on_fly.srcs/sources_1/new/cos_lut.sv
  E:/work/crypto/twiddle_lut/files/rom_async.sv
  E:/work/crypto/twiddle_lut/files/sin_lut.sv
}
read_verilog -library xil_defaultlib {
  E:/work/vivado/tw_on_fly/tw_on_fly.srcs/sources_1/new/cos_lut_wr.v
  E:/work/crypto/twiddle_lut/files/sine_lut_wr.v
  E:/work/vivado/tw_on_fly/tw_on_fly.srcs/sources_1/new/tw_calc.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top tw_calc -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef tw_calc.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file tw_calc_utilization_synth.rpt -pb tw_calc_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
